### ISSUE TITLE
Streamlining the menu items with the layout names

### ISSUE THREAD

**Issue by andrejrenard** [emmasuzuki/EasyForm#2]
Objective: To define menu and forms in XML only

A menu item name in the the menus.xml file is also the name of its linked layout file. Thus an item named "form_1" will have a corresponding form_1.xml in the layout resources. 

I modified the MainActivity.java file as shown.

```java
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        if (savedInstanceState == null) {
            Fragment fragment = new IqFormFragment();
            Bundle bundle = new Bundle();
            bundle.putString("name", "form_1");
            fragment.setArguments(bundle);
            getFragmentManager().beginTransaction()
                    .add(R.id.form, fragment)
                    .commitAllowingStateLoss();
        }
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menus, menu);

        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        replaceForm(item.getItemId());

        return true;
    }

    private void replaceForm(@IdRes int menuId) {
        Fragment fragment = new IqFormFragment();
        Bundle bundle = new Bundle();
        bundle.putString("name", getResources().getResourceEntryName(menuId));
        fragment.setArguments(bundle);

        getFragmentManager().beginTransaction()
                .replace(R.id.form, fragment)
                .commitAllowingStateLoss();
    }
}
```

There will be only one generic FormFragment class (here IqFormFragment). But I haven't yet looked to how to implement the setRegexPattern of the  EditTextFormFragment file in the sample.

```java
public class IqFormFragment extends Fragment {

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        Bundle bundle = getArguments();
        @IdRes int formId = getResources().getIdentifier(bundle.getString("name"),"layout",getContext().getPackageName());

        return inflater.inflate(formId, container, false);
    }
}
```

**Comment by emmasuzuki** [comment]
"A menu item name in the the menus.xml file is also the name of its linked layout file. Thus an item named "form_1" will have a corresponding form_1.xml in the layout resources."
is an app level feature and your MainActivity should do its job already. 

When you mention you need to figure out how to implement `setRegexPattern` in Fragment, do you need to set regex dynamically? 
For all of forms that you are trying to instantiate via the generic Fragment class?

**Comment by andrejrenard** [comment]
I believe so.  It would be nice to be able to link a pattern to a field in the XML file.

**Comment by emmasuzuki** [comment]
If dynamic, you would do in java (`setRegexPattern`).   
If static, you can set a property, `app:regexPattern="[0-9]+"`, in xml.  
Both channels are available in current version.

**Comment by andrejrenard** [comment]
Super
