### ISSUE TITLE
unfocus + non-EasyForm inputs make validation fail

### ISSUE THREAD

**Issue by Harti** [emmasuzuki/EasyForm#8]
Sorry for bothering you again. 😅 

Note: This bug only happens with the `showErrorOn` attribute being set to `unfocus` and there is a foreign View in the form (presumably because of what happens on `EasyForm.java:118`). 

Using the following layout, the submit button will never become enabled. I assume it's because the foreign library's ViewGroup can't be validated by the `FormValidator`:

`layout.xml`
```
    <com.emmasuzuki.easyform.EasyForm
            android:id="@+id/form_room"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:submitButton="@+id/form_room_submit"
            app:showErrorOn="unfocus">

        <com.emmasuzuki.easyform.EasyTextInputLayout
                android:id="@+id/form_room_name"
                android:hint="@string/form_room_name"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

        <LinearLayout
                android:id="@+id/form_room_group_number_floor"
                android:layout_below="@id/form_room_name"
                android:orientation="horizontal"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

            <com.emmasuzuki.easyform.EasyTextInputLayout
                    android:id="@+id/form_room_number"
                    android:hint="@string/form_room_number"
                    android:layout_width="0dp"
                    android:layout_weight="3"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/form_room_name"
                    app:errorMessage="@string/form_error_empty"
                    app:errorType="empty" />

            <com.shawnlin.numberpicker.NumberPicker
                    android:id="@+id/form_room_floor"
                    android:hint="@string/form_room_floor"
                    android:layout_width="0dp"
                    android:layout_weight="2"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/form_room_number"
                    app:np_orientation="horizontal"
                    app:np_min="-3"
                    app:np_max="8"
                    app:np_value="0" />
        </LinearLayout>

        <Button
                android:id="@+id/form_room_submit"
                android:text="@string/form_room_submit"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_below="@id/form_room_group_number_floor" />

    </com.emmasuzuki.easyform.EasyForm>
``` 

It *works* if I only put `EasyTextInputLayout`s into the `LinearLayout`. It *also works* if I keep the foreign View and set the error check to `change`. 

One idea would be to implement an Interface:
```
public interface EasyForm.Validatable {
    boolean isValid();
}
```
and consider children always valid unless they implement this interface. Then I could extend the `NumberPicker` class to implement the interface and the method. And you could then rely on Inputs to have a validation method.

This is just a minor bug, I can easily work with the library using the `change` attribute value. So don't worry and take your time.

Thanks in advance,

Harti

**Comment by emmasuzuki** [comment]
Don't be sorry, I appreciate your feedback :) 

I found out the issue is at https://github.com/emmasuzuki/EasyForm/blob/master/library/src/main/java/com/emmasuzuki/easyform/EasyForm.java#L190

It is doing the exact equal. I should do `>=` instead to cover a case where it is only 1 validatable field.

That means this bug only occurs on very specific condition
     - `showErrorOn` is "unfocus" AND there is only 1 field which has an `errorType`

Thus, you can use third party view just fine but you need at least 1 more `EasyTextInputLayout` with an `errorType`. 

For now, these should work 
     - add `errorType="empty"` or any validation to `form_room_name` OR
     - add 1 more text field with validation OR
     - use `showErrorOn="change"`

**Comment by emmasuzuki** [comment]
Also exposing a custom validation interface sounds like a good idea. I will put into a consideration for the next update.
