### ISSUE TITLE
EasyForm.validate() should always validate

### ISSUE THREAD

**Issue by Harti** [emmasuzuki/EasyForm#9]
On `EasyForm.java:104` you provide the `validate()` method. It only performs validation if the `showErrorOn` attribute is set to `unfocus`. I think it would be better to be able to manually trigger validation without relying on certain attributes to be set. 

My use case is that I put a second "submit" button into my AppBar/Toolbar, and it uses the same method as the submit button does (which checks if the form is valid first before proceeding):
```
    protected void onFormSubmit()
    {
        getForm().validate();
        if(!getForm().isValid())
        {
            return;
        }
        // ... interpret fields
    }
```
But because my form is set to onChange (due to #8), the `validate()` method won't display errors on my form. So the user presses the button and sees nothing.

/edit: To work around this for now, I put regexPattern=".*" on my inputs like you said in #8 and am now able to use "unfocus" again.

**Comment by emmasuzuki** [comment]
Fixed.
